version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  
  - package-ecosystem: npm
    directory: "/frontend"
    schedule:
      interval: "monthly"
  
  - package-ecosystem: gradle
    directory: "/backend"
    schedule:
      interval: "monthly"
  
  - package-ecosystem: docker
    directories:
      - "/backend"
      - "/frontend"
    schedule:
      interval: "monthly"
