apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-backend" (include "livechat.fullname" .) }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "livechat.fullname" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "livechat.fullname" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: "/actuator/health/liveness"
              port: 8081
            initialDelaySeconds: 15
          readinessProbe:
            httpGet:
              path: "/actuator/health/readiness"
              port: 8081
            initialDelaySeconds: 5
          envFrom:
            - configMapRef:
                name: {{ include "livechat.fullname" . }}
          env:
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mongodb.fullname" .Subcharts.mongodb }}
                  key: mongodb-passwords
