apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-backend" (include "livechat.fullname" .) }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
