apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "livechat.fullname" . }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.backend.ingress.host | quote }}
        - {{ .Values.frontend.ingress.host | quote }}
      secretName: {{ default (printf "%s-tls" (include "livechat.fullname" .)) .Values.ingress.tls.secretName | quote }}
  {{- end }}
  rules:
    {{- with .Values.backend.ingress }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- with .pathType }}
            pathType: {{ . }}
            {{- end }}
            backend:
              service:
                name: {{ printf "%s-backend" (include "livechat.fullname" $) }}
                port:
                  number: {{ $.Values.backend.service.port }}
          {{- end }}
    {{- end }}
    {{- with .Values.frontend.ingress }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- with .pathType }}
            pathType: {{ . }}
            {{- end }}
            backend:
              service:
                name: {{ printf "%s-frontend" (include "livechat.fullname" $) }}
                port:
                  number: {{ $.Values.frontend.service.port }}
          {{- end }}
    {{- end }}
