apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-frontend" (include "livechat.fullname" .) }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "livechat.fullname" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "livechat.fullname" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: "/healthz"
              port: {{ .Values.frontend.service.port }}
            initialDelaySeconds: 15
          readinessProbe:
            httpGet:
              path: "/readyz"
              port: {{ .Values.frontend.service.port }}
            initialDelaySeconds: 5
          envFrom:
            - configMapRef:
                name: {{ include "livechat.fullname" . }}
